[tool.poetry]
name = "rex-lib"
version = "0.0.3"
license = "Apache2.0"
description = "Rex is a tool for creating Robotic Environments with jaX."
authors = ["Bas van der Heijden <d.s.vanderheijden@tudelft.nl>"]
homepage = "https://github.com/bheijden/rex"
repository = "https://github.com/bheijden/rex"
documentation = "https://github.com/bheijden/rex"
packages = [
    { include = "rex" },
]

[tool.poetry.dependencies]
python = "^3.9.0"
supergraph = "^0.0.8"  # todo: Latest version? todo: supergraph depends on numpy < 2.0...
gymnasium = "^0.28.1"
jax = "^0.4.1"  # 0.4.29?
equinox="0.11.4"  # Required for sysid
# todo: , evosax="0.1.6" (sysid), optax="0.2.2" (ppo)
flax = "^0.8.4"
distrax = "^0.1.5"
termcolor = "^2.1.1"
networkx = "^3.1"
matplotlib = "^3.6.2"  # 3.7.1 allows for plotting in pycharm, 3.9.0 does not show plots.
seaborn = "^0.12.1"
dill = "^0.3.6"  # Provides tools for investigating broken pickles, and tools for creating better pickles.
tqdm = "^4.64.1"

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
# https://python-poetry.org/docs/pyproject/#extras
# poetry install --all-extras or poetry install -E paper or poetry install --all-extras or poetry install --extras "paper"
#jupyter = { version = "^1.0.0", optional = true }
#jupyterlab = { version = "^4.0.3", optional = true }
#ipywidgets = { version = "^8.0.7", optional = true }
#brax = { version = "^0.9.4", optional = true }
#modern-robotics = { version = "^1.1.1", optional = true }
#mujoco = { version = "^3.1.1", optional = true }
#mujoco-mjx = { version = "^3.1.1", optional = true }
#opencv-contrib-python = { version = "^4.9.0.80", optional = true}
#equinox = { version = "^0.11.3", optional = true }
#optimistix = { version = "^0.0.6", optional = true }
#evosax = { version = "^0.1.5", optional = true }


#[tool.poetry.extras]
#sysid = ["jupyter", "jupyterlab", "ipywidgets", "brax", "modern-robotics", "mujoco-mjx", "mujoco", "opencv-contrib-python",
#         "equinox", "optimistix", "evosax"]

[tool.poetry.dev-dependencies]
black = "^23.3.0"
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
flake8 = ">=3"
flake8-bugbear = "^23.6.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "rex/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "master"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"
