model: "SAC"
env: "async-sbx-eps10-disc-pendulum-envs.pendulum.ode.world-wall-clock-real-time-frequency-latest-2023-08-14-1110"
parameters:
  num_envs: 4
  gamma: 0.9427860014779296
  learning_rate: 0.0016222232059594057
  batch_size: 2048
  buffer_size: 10000
  tau: 0.08
  ent_coef: "auto"
  qf_learning_rate: 0.06341856428465494
  log_std_init: -3
  net_arch: "small"
