# This workflow is based on the workflow from https://github.com/patrick-kidger/equinox
name: Build docs

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # Pin a specific version of uv.
          version: "0.5.5"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev

      - name: Install docs dependencies
        run: uv pip install -r docs/requirements.txt

      - name: Build docs
        run: make build_docs

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: site  # where `mkdocs build` puts the built site

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
