name: Run tests

on:
  pull_request:
#  push:
#    branches:
#      - master

jobs:
  run-test:
    strategy:
      matrix:
        python-version: [3.11]
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # Pin a specific version of uv.
          version: "0.5.5"
          
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        # todo: maybe not extras, but all dev and tests requirements?
        run: uv sync --all-extras --dev --group tests

#      - name: Checks with pre-commit (requires .pre-commit-config.yaml)
#        uses: pre-commit/action@v2.0.3

      - name: Run tests
        run: make run_tests


